version: "2.0"
services:
    mongo:
        image: mongo
        networks:
            net1:
                ipv4_address: 192.188.2.10
    amf:
        build:
                context: ./amf
                dockerfile: Dockerfile
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.2
    upf:
        build:
                context: ./upf
                dockerfile: Dockerfile
        privileged: true
        depends_on:
            - mongo
        devices:
              - "/dev/net/tun:/dev/net/tun"
        cap_add:
              - NET_ADMIN
        network_mode: "host"
    smf:
        build:
                context: ./smf
                dockerfile: Dockerfile
        depends_on:
            - mongo
            - upf
        networks:
            net1:
                ipv4_address: 192.188.2.4
    hss:
        build:
                context: ./hss
                dockerfile: Dockerfile
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.3
    pcrf:
        build:
                context: ./pcrf
                dockerfile: Dockerfile
        depends_on:
            - mongo
            - smf
        networks:
            net1:
                ipv4_address: 192.188.2.5
    webapp:
        build:
                context: ./webapp
                dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
            - DB_URI=mongodb://192.188.2.10:27017/free5gc
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.11
networks:
    net1:
        ipam:
            driver: default
            config:
                - subnet: 192.188.2.0/24
