version: "2.0"
services:
    db:
    	image: mongo
    	container_name: mongodb
    	command: mongod
    	expose:
      	    - "27017"
    	networks:
            - mongo
    	volumes:
            - ./mongodb:/data/db
        network_mode: "host"

    free5gc:
    	image: free5gc
    	container_name: free5gc
    	privileged: true
        depends_on:
            - mongo
        devices:
              - "/dev/net/tun:/dev/net/tun"
        cap_add:
              - NET_ADMIN
        network_mode: "host"
